# This file was generated by GoReleaser. DO NOT EDIT.
cask "lytecache" do
  version "0.2.6"

  on_macos do
    on_intel do
      sha256 "409c120b8d3ae7d912c30d8adfb58bbf591fd6622ebe7f59ac5f1a595dbf5990"
      url "https://github.com/lytecache/lytecache-cli/releases/download/v#{version}/lytecache_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "61296746f782dc395c67e5c17599f9cb4639990d6576fb12a73114fb2dc15ee9"
      url "https://github.com/lytecache/lytecache-cli/releases/download/v#{version}/lytecache_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9cf4a3aef3697b5edb1d15bf5c269ed8227ae0a3b55c126da02d58ebfe901d59"
      url "https://github.com/lytecache/lytecache-cli/releases/download/v#{version}/lytecache_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0527d18f14cf3fba5488cb1220c8a72ce1ba98e93a6b24538179c4dcb20f18bf"
      url "https://github.com/lytecache/lytecache-cli/releases/download/v#{version}/lytecache_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lytecache"
  desc "Command-line tool for interacting with lytecache database files."
  homepage "https://lytecache.github.io/lytecache"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lytecache"

  postflight do
    system_command "/bin/sh", args: ["-c", "\"#{staged_path}/lytecache\" service install || true"]
  end

  # No zap stanza required

  caveats <<~EOS
    lytecache ui defaults to http://127.0.0.1:7070, first-run credentials admin/admin.
    Run it once with: lytecache ui
    Or start the background service (already registered for you): lytecache service start
    See: https://github.com/lytecache/lytecache-cli/blob/main/docs/ui.md
  EOS
end
