# This file was generated by GoReleaser. DO NOT EDIT.
cask "lytecache" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2bbd6bd3f3a77c02a8a4703e1f201e1fd06cd403892cbf98a047fc243505d507"
      url "https://github.com/lytecache/lytecache-cli/releases/download/v#{version}/lytecache_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "92ae4333751ed76c3afd092d53c64590a5f525ccabe777361e073b39e8a1ecfb"
      url "https://github.com/lytecache/lytecache-cli/releases/download/v#{version}/lytecache_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6f83823b13c9f0038140225b9713eb74b8dc2d2b67161fc038ef71365892a901"
      url "https://github.com/lytecache/lytecache-cli/releases/download/v#{version}/lytecache_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d68bc92722612c9dd3f2eb1212a028f3e0e95f76c5129c6ffb3597677ca74550"
      url "https://github.com/lytecache/lytecache-cli/releases/download/v#{version}/lytecache_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lytecache"
  desc "Command-line tool for interacting with lytecache database files."
  homepage "https://lytecache.github.io/lytecache"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lytecache"

  # No zap stanza required

end
