# This file was generated by GoReleaser. DO NOT EDIT.
cask "lytecache" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "b74eacab897c864584bea7eea9f58acfa8a88138bcab12f10335de71346cf539"
      url "https://github.com/lytecache/lytecache-cli/releases/download/v#{version}/lytecache_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "38bb8d63c03bca618300418d20da1ffb85c4b8ab1701517cf01730a42cd9d73a"
      url "https://github.com/lytecache/lytecache-cli/releases/download/v#{version}/lytecache_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "20149a6a285a5e6a8f587721f0588f983a3ebbd2325b06704f1048642f9d19a4"
      url "https://github.com/lytecache/lytecache-cli/releases/download/v#{version}/lytecache_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fddfc4ed4d21c5436b2f2116da006d791586f6b1d8746dde4ae0cdbb5402bf1f"
      url "https://github.com/lytecache/lytecache-cli/releases/download/v#{version}/lytecache_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lytecache"
  desc "Command-line tool for interacting with lytecache database files."
  homepage "https://lytecache.github.io/lytecache"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lytecache"

  # No zap stanza required

  caveats <<~EOS
    lytecache ui defaults to http://127.0.0.1:7070, first-run credentials admin/admin.
    Run it once with: lytecache ui
    Or in the background: lytecache service install && lytecache service start
    See: https://github.com/lytecache/lytecache-cli/blob/main/docs/ui.md
  EOS
end
